### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pyrox0** [pyrox0/archive-run#1]
This is non-exhaustive, and in no particular order.
- [ ] Finish org templates
	- [ ] Details
	- [ ] List
- [ ] Finish event templates
	- [ ] Details
	- [ ] List
- [ ] Finish charity templates
	- [ ] Details
	- [ ] List
- [ ] Finish run templates
	- [ ] Details
	- [ ] List
- [ ] Add ingestion forms
	- [ ] Events (below will auto-populate runs)
		- [ ] From (GDQ Tracker)[https://github.com/gamesdonequick/donation-tracker]
		- [ ] From (Oengus)[https://oengus.io]
	- [ ] Manual Event Import
	- [ ] Manual Run Import
	- [ ] Charity Creation
	- [ ] Organization Creation
		- [ ] Provide a way to auto-ingest events from GDQ tracker/oengus? Need to see how complicated that would be
